Nick Proskurin 181.1, task A: HashMap, attempt 1
MCPN/HashMap pull request #1
Opened 2019-03-05 18:53 UTC by MCPN

/shrug
¯\_(ツ)_/¯

2019-03-23 22:22 UTC, glebshp commented on HashMap.h
> +    using iterator = typename std::list<std::pair<const KeyType, ValueType>>::iterator;
const_iterator и InitList - названия в разном стиле

2019-03-23 22:22 UTC, glebshp commented on HashMap.h
> +    HashMap(const Hash &hshr=Hash()): sz(0), cap(START_SIZE), hasher(hshr), items(), table() {
= отбивается пробелами

2019-03-23 22:22 UTC, glebshp commented on HashMap.h
> +    HashMap(const Hash &hshr=Hash()): sz(0), cap(START_SIZE), hasher(hshr), items(), table() {
и hshr - непонятное название переменной

2019-03-23 22:23 UTC, glebshp commented on HashMap.h
> +    size_t MAX_FACTOR = 2, MIN_FACTOR = 8, START_SIZE = 5;
сделать public const static и перенести в начало

2019-03-23 22:23 UTC, glebshp commented on HashMap.h
> +            for (auto elem : other) {
const auto

2019-03-23 22:24 UTC, glebshp commented on HashMap.h
> +    HashMap(const InitList &lst, const Hash &hshr=Hash()): HashMap(hshr) {
пробелы

2019-03-23 22:24 UTC, glebshp commented on HashMap.h
> +        for (auto elem : lst) {
const

2019-03-23 22:24 UTC, glebshp commented on HashMap.h
> +        for (auto elem : lst) {
и lst не лучшее название

2019-03-23 22:24 UTC, glebshp commented on HashMap.h
> +    HashMap& operator =(const HashMap &other) {
пробел

2019-03-23 22:25 UTC, glebshp commented on HashMap.h
> +        if (MAX_FACTOR * sz > cap) {
MAX_FACTOR - это марка косметики, и, если это не product placement, то константу можно назвать более информативно

2019-03-23 22:26 UTC, glebshp commented on HashMap.h
> +    void rehash(bool shrink=false) {
Разумнее сделать три метода:
1. Изменение до заданного размера
2. Увеличение
3. Уменьшение

2019-03-23 22:27 UTC, glebshp commented on HashMap.h
> +            if (table[pos].second == 1 && table[pos].first -> first == key) {
-> не отбивают пробелами

2019-03-23 22:29 UTC, glebshp requested changes
Я, возможно, что-то неправильно смотрел, но где итератор по таблице?

2019-03-24 08:01 UTC, MCPN commented
Разве не достаточно просто определить методы begin() и end()? Специально для таблицы я итератор естественно не писал, вместо этого сослался на итератор списка.

2019-03-24 09:58 UTC, MCPN commented on HashMap.h
> +        if (MAX_FACTOR * sz > cap) {
Переименую в MAX_LOAD_FACTOR (аналогично тому, как это сделано в unordered_map) и MIN_LOAD_FACTOR соответственно.

2019-03-25 22:23 UTC, glebshp commented on HashMap.h
> +            for (auto elem : other) {
а где const?

2019-03-25 22:32 UTC, glebshp commented on HashMap.h
> +            shrink();
не то, такая логика стала только менее понятной.
Должно быть:
1. Функция rehash, которая принимает точный размер, в который надо изменить
2. Функция проверки, не надо ли увеличить, функция проверки, не надо ли уменьшить. Либо общая функция, которая возвращает новый размер, до которого надо делать resize.
3. Далее либо предыдущие функции вместе вызываются в местах, где может произойти изменение, но проще сделать общую функцию "проверь и поменяй", которая уже содержит в себе проверку, что надо сделать, и, если надо, делает

2019-03-25 22:34 UTC, glebshp commented on HashMap.h
> +            erase(items.begin()->first);
Так удалять довольно не эффективно, явно удаление оптом можно реализовать дешевле (с точки зрения времени работы)

2019-03-25 22:38 UTC, glebshp commented on HashMap.h
> +            items.erase(items.begin());
разумнее не вызывать каждый раз erase, а пройтись по старому списку а в конце удалить его оптом

2019-03-25 22:39 UTC, glebshp requested changes
Мелочи + функции проверки на resize и собственно resize сейчас организованы странно

2019-03-27 23:41 UTC, glebshp commented on HashMap.h
> +            for (const auto elem : other) {
const auto&

2019-03-27 23:42 UTC, glebshp commented on HashMap.h
> +        for (const auto elem : initializer) {
const auto&

2019-03-27 23:42 UTC, glebshp commented on HashMap.h
> +            for (const auto elem : other) {
const auto& здесь и далее, не буду уже отмечать

2019-03-27 23:47 UTC, glebshp commented on HashMap.h
> +        cap /= SHRINK_FACTOR;
хорошо бы не уводить в меньше чем стартовый размер

2019-03-27 23:48 UTC, glebshp commented on HashMap.h
> +        if (MAX_LOAD_FACTOR * sz > cap) {
А теперь ещё можно засунуть в один метод (resize_if_needed например) проверки размеров, вызов expand/shrink и resize

2019-03-27 23:48 UTC, glebshp requested changes
Разные мелочи + я всё ещё хочу clear без erase

2019-03-28 08:11 UTC, MCPN commented on HashMap.h
> +            items.erase(items.begin());
Сделал без erase (не совсем уверен, что то, что требовалось), стало работать чуть дольше. На всякий случай залью, но вообще странно.

2019-03-28 18:38 UTC, glebshp approved these changes
Норм

2019-03-28 18:57 UTC, merged